version: '3'
services:
  db:
    image: "postgres:9"
    environment:
      - POSTGRES_USER=${ENV_DB_USER_NAME}
      - POSTGRES_PASSWORD=${ENV_DB_USER_PASSWORD}
      - POSTGRES_DB=${ENV_DB_NAME}
    volumes:
      - "./data_base/script:/docker-entrypoint-initdb.d:ro"
    ports:
      - ${ENV_DB_PORT}:5432

  library-web-service:
    build: ./project_4_web_service
    environment:
      - VAR_SLEEP=10 # gives time for the database to boot before the application
      - VAR_POSTGRES_SERVICE=db # set the postgres service name (without docker-compose, default is localhost)
      - ENV_DB_USER_NAME # set the user name for db from .env
      - ENV_DB_USER_PASSWORD # set the user password for db from .env
      - ENV_DB_NAME # set from .env
      - ENV_DB_PORT # set from .env
      - ENV_WEB_SERVICE_PORT # default=8000
      - ENV_WEB_SERVICE_CONTEXT_PATH # default=/
      - ENV_RESERVATION_DURATION # duration of a reservation in hours default=48
    ports:
      - "${ENV_WEB_SERVICE_PORT}:${ENV_WEB_SERVICE_PORT}"
      
  library-web-app:
    build: ./project_4_web_app
    environment:
      - VAR_WEB_SERVICE=library-web-service # set the adress host for the postgres service (without docker-compose, default is localhost)
      - ENV_WEB_SERVICE_PORT
      - ENV_WEB_APP_PORT
    ports:
      - "${ENV_WEB_APP_PORT}:${ENV_WEB_APP_PORT}"
  
