version: '3'
services:
  db:
    image: "postgres:9"
    environment:
      - POSTGRES_USER=${ENV_DB_USER_NAME}
      - POSTGRES_PASSWORD=${ENV_DB_USER_PASSWORD}
      - POSTGRES_DB=${ENV_DB_NAME}
    volumes:
      - "./project_4_web_service/create_tables.sql:/docker-entrypoint-initdb.d/1-tables.sql"
      - "./project_4_web_service/add_entities.sql:/docker-entrypoint-initdb.d/2-data.sql"
  library-web-service:
    build: ./project_4_web_service
    environment:
      - VAR_SLEEP=10 # gives time for the database to boot before the application
      - VAR_POSTGRES_SERVICE=db # set the postgres service name (without docker-compose, default is localhost)
      - VAR_DB_USER_NAME=${ENV_DB_USER_NAME} # set the user name for db from .env
      - VAR_DB_USER_PASSWORD=${ENV_DB_USER_PASSWORD} # set the user password for db from .env
      - VAR_WEB_SERVICE_PORT=${ENV_WEB_SERVICE_PORT}
    ports:
      - "${ENV_WEB_SERVICE_PORT}:${ENV_WEB_SERVICE_PORT}"
  library-web-app:
    build: ./project_4_web_app
    environment:
      - VAR_WEB_SERVICE=library-web-service # set the adress host for the postgres service (without docker-compose, default is localhost)
      - VAR_WEB_SERVICE_PORT=${ENV_WEB_SERVICE_PORT}
      - VAR_WEB_APP_PORT=${ENV_WEB_APP_PORT}
    ports:
      - "${ENV_WEB_APP_PORT}:${ENV_WEB_APP_PORT}"
  
